# Fichier de config commun aux differentes applications clientes du Serveur de Config
server:
  application:
    conf:
      dir: ${user.dir}/logs
  use-forward-headers: true
  address: localhost
  port: 8089

spring:
  application:
    name: automatesw
  session:
    store-type: none
webapp:
  actuator:
    username: admin
    password: admin
  security:
    restPrefix: ${webapp.url.services}/rest
  url:
    contextRoot: /automatesw
    services:  ${webapp.url.contextRoot}/services

management:
  context-path: /management
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
action:
  delay:
    default: 1500
    temps:
      feu: 150000
      eau: 120000
      vent: 120000
      ligth: 190000
      dark: 120000
      magic: 80000
      geant: 120000